### ISSUE TITLE
Change cloaks page so it can't be easily scraped

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/runbook#31]
The cloaks page (from #23) has a table with a lot of info about FOSS members that is _really_ easy to scrape. It'd be appreciated if emails and RIT usernames were removed. While these are technically in the `foss_profiles` repo, they're not as blatantly easy to scrape there.

Also, usage of `[at]`, like used in #29, is still easy to scrape. If you want email and RIT username to be accessible, it might be better to defer to another location, such as `foss_profiles`.

**Comment by jwflory** [comment]
@ct-martin That's a fair point. Originally this info was in the FOSSRIT/library repo and I migrated it over as-is. I am required by Freenode to maintain this information for the cloaks, but leaving them out in the public isn't the best approach.

One approach is to migrate the table data to a public Google Sheets doc and link to it from the Runbook page. Still not ideal and not 100% FOSS, but I am thinking this is the best middle-ground approach to addressing the organizational need to maintain this data, but also protecting privacy of folks who do have a cloak.

Thoughts?

**Comment by ct-martin** [comment]
@jwflory part of what I was trying to get at in [this issue](https://github.com/FOSSRIT/tasks/issues/105) was having public what/where information is, but the information itself doesn't have to be public (e.g. passwords and specific billing info). If there was a spreadsheet that wasn't public, but its existence was documented, I don't have an issue with that.

Also, I do not see any information about Freenode's requirements for cloaks, this would be good to link to on the page.

**Comment by jwflory** [comment]
At the time, I was asked to keep this information visible for Freenode staff. This was communicated to me as internal policy by a staff member over private message. I can follow up with Freenode staff to see if this list still needs to be public or not, since the conversation was sometime in 2017.
